# Generated by Django 5.1.1 on 2024-09-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boxNumber", models.CharField(max_length=30, null=True)),
                ("organism", models.CharField(max_length=100, null=True)),
                ("idNumber", models.CharField(max_length=100, null=True)),
                ("copySaved", models.PositiveBigIntegerField(null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("isolationSource", models.CharField(max_length=300, null=True)),
                ("alternateDesignation", models.CharField(max_length=300, null=True)),
                ("receivedFrom", models.CharField(max_length=300, null=True)),
                ("ReceivedDate", models.DateField(null=True)),
                ("originallyReceivedFrom", models.CharField(max_length=300, null=True)),
                ("additionalInfo", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(null=True)),
                ("storage", models.TextField(null=True)),
                ("receivedDate", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("catalogNumber", models.CharField(max_length=50)),
                ("link", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(null=True)),
                ("orderedDate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
