# Generated by Django 5.1.1 on 2024-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culture",
            name="additionalInfo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="alternateDesignation",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="idNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="isolationSource",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="culture",
            name="originallyReceivedFrom",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
